sudo: required
services: 
  - docker
before_install:
  - docker build -t joevarkey/1 -f Dockerfile.dev .
script:
  - docker run joevarkey/1 npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-277177018786"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY


